default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 0.0.0.0
  database: experts_directory
  username: experts_directory
  password: experts_directory!23
  port: 5453

test:
  <<: *default
  database: experts_directory_test

production:
  <<: *default
  database: experts_directory_production
  username: experts_directory
  password: <%= ENV['EXPERTS_DIRECTORY_DATABASE_PASSWORD'] %>
